default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args:
                - '--maxkb=10000'
          - id: end-of-file-fixer
            exclude: '\.ipynb$'
          - id: check-toml
          - id: check-xml
          - id: check-case-conflict
          - id: check-symlinks
          - id: check-merge-conflict
            stages:
                - commit
                - merge-commit
                - manual
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
            language_version: python3.10
            args: [--config=./pyproject.toml]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.284
      hooks:
          - id: ruff
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.1
      hooks:
          - id: prettier
            stages:
                - commit
                - manual
            exclude: \{\{cookiecutter.repo_name\}\}/
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.5.0
      hooks:
          - id: commitlint
            additional_dependencies: ['@commitlint/config-conventional']
            stages:
                - commit-msg
