name: data-science-project-template
channels:
    - conda-forge
dependencies:
    - python=3.10.9
    - cookiecutter=2.1.1
    - pre-commit=3.3.3
    - pylint=2.16.1
    - pytest=7.2.1
    - pytest=7.2.1
