default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args:
                - '--maxkb=10000'
          - id: end-of-file-fixer
            exclude: '\.ipynb$'
          - id: check-toml
          - id: check-xml
          - id: check-case-conflict
          - id: check-symlinks
          - id: check-merge-conflict
            stages:
                - commit
                - merge-commit
                - manual
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.5.0
      hooks:
          - id: commitlint
            additional_dependencies: ['@commitlint/config-conventional']
            stages:
                - commit-msg
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
            stages:
                - commit
                - manual
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
            language_version: python3.10
            args: [--config=./pyproject.toml]
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
    {%- if cookiecutter.install_jupyter == 'yes' %}
          - id: nbqa-black
            name: nbqa-black
            entry: nbqa black
            language: system
            files: \.ipynb
          - id: nbqa-pylint
            name: nbqa-pylint
            entry: nbqa pylint
            language: system
            files: \.ipynb
            args:
                - --disable=pointless-statement,duplicate-code,expression-not-assigned
                - --const-rgx=(([A-Z_][A-Z0-9_]*)|(__.*__)|([a-z_][a-z0-9_]{0,50}))$
    {%- endif %}
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.1
      hooks:
          - id: prettier
            stages:
                - commit
                - manual
            exclude: data/
