name: '{{cookiecutter.env_name}}'
channels:
    - conda-forge
dependencies:
    {%- if cookiecutter.install_jupyter == 'yes' %}
    - nbqa=1.6.1
    - jupyter=1.0.0
    {%- endif %}
    - python=3.10.9
    - pre-commit=3.3.3
    - pylint=2.16.1
